services:
  web:
    build:
      context: .
      dockerfile: ffw/dockerFFW
    container_name: web-container
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=ffwdb;Username=ffwuser;Password=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - ffw-network

  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ffwdb
      - POSTGRES_USER=ffwuser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ffw-network

networks:
  ffw-network:
    driver: bridge

volumes:
  pgdata:
